[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "pillow>=11.3.0",
    "python-telegram-bot>=22.4",
    "schedule>=1.2.2",
]
